# Generated by Django 4.0.4 on 2022-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CALC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_op1', models.CharField(max_length=20)),
                ('value_op2', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Value_R',
        ),
    ]
