# Generated by Django 4.0.4 on 2022-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CALC', '0002_operands_delete_value_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='operands',
            name='operator',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
