# Generated by Django 4.0.4 on 2022-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CALC', '0005_alter_operands_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operands',
            name='operator',
            field=models.CharField(max_length=1),
        ),
    ]
