# Generated by Django 4.0.4 on 2022-04-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CALC', '0006_alter_operands_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operands',
            old_name='operator',
            new_name='operand',
        ),
    ]
